# Generated by Django 4.0.1 on 2022-01-24 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='yazarı',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='relationships.creator'),
        ),
    ]
