# Generated by Django 4.0.1 on 2022-01-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_alter_language_yazarı'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='yazarı',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relationships.creator'),
        ),
        migrations.CreateModel(
            name='Frameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Dil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.language')),
            ],
        ),
    ]
