# Generated by Django 4.0.1 on 2022-01-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0002_alter_student_options_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
